apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: grafana
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 10.1.4
      helm:
        releaseName: grafana
        valueFiles:
          - $values/apps/values/grafana/values.yaml
        skipCrds: false
    - repoURL: git@github.com:lotechdevops/apps-argocd.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observabilidade
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true  
    retry:
      limit: 5
      backoff:
        duration: "5s"
        factor: 2
        maxDuration: "3m"
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true